### PR TITLE
mba: Support named measured boot policies

### PR DESCRIPTION
**Pull request by niteeshkd**
Similar to named runtime policies, it allows the operator to add, show, delete, update and use measured boot policies with names. It also allows to list the measured boot policies.

### CODE REVIEW

**Comment by ansasaki** [comment]
Sorry for taking a long time to get to this. Thank you for the contribution!

This adds a lot of new API endpoints to the verifier under the `/mbpolicies/` I believe the API version needs to be bumped.

Could you please add tests? Ideally end-to-end tests should be added to the https://github.com/RedHat-SP-Security/keylime-tests repository, but at least some unit tests should be added.

**Comment by niteeshkd** [comment]
> Sorry for taking a long time to get to this. Thank you for the contribution!
> 
> This adds a lot of new API endpoints to the verifier under the `/mbpolicies/` I believe the API version needs to be bumped.
> 

Sure, i will bump the API version.

> Could you please add tests? Ideally end-to-end tests should be added to the https://github.com/RedHat-SP-Security/keylime-tests repository, but at least some unit tests should be added.

Testing these mbpolicy related options with keylime_tenant reqires verifier to be running. So, i think adding tests to  https://github.com/RedHat-SP-Security/keylime-tests is better option which i can do later.

**Comment by niteeshkd** [comment]
> Ideally end-to-end tests should be added to the https://github.com/RedHat-SP-Security/keylime-tests repository, but at least some unit tests should be added.

I have submitted the keylime-tests [PR#592](https://github.com/RedHat-SP-Security/keylime-tests/pull/592) to perform various tests about supporting the named measured boot policies as mentioned in this PR.

**Comment by maugustosilva** [comment]
After discussing on the monthly video-meeting in June/2024. I am about to merge it.

**Review by maugustosilva — APPROVED** [review]

**Pull request merged**
