### PR TITLE
installer.sh package / pip changes

### PR DESCRIPTION
**Pull request by bu3alwa**
I hope this is what was needed for that issue. Sorry not sure how to link the PR to the issue. #256

### CODE REVIEW

**Comment by lukehinds** [comment]
awesome, thanks for your contribution @bu3alwa - I will shortly do a review and sponsor you with this being your first pull request to keylime. welcome to the community.

**Comment by bu3alwa** [comment]
Just to confirm do you want `python3-simplejson python3-tornado` to 108 in `PYTHON_PREIN`?

Otherwise they exist in `PYTHON_DEPS` right now 

`PYTHON_DEPS="gcc gcc-c++ openssl-devel python3-yaml python3-requests swig python3-cryptography wget git python3-tornado python3-zmq python3-simplejson"`

**Comment by lukehinds** [comment]
sorry, i see it now..your change has them in place. So its just a case of removing `PYTHON_PIPS="m2crypto"` (we no longer use m2crypto).

**Comment by lukehinds** [comment]
Looks good @bu3alwa , just one last thing. Could you squash your 2 commits into a single commit message:

https://github.com/keylime/keylime/blob/master/CONTRIBUTORS.md#squash-commits

You should be able to do `git rebase -i HEAD~2`

**Comment by jetwhiz** [comment]
> 
> 
> sorry, i see it now..your change has them in place. So its just a case of removing `PYTHON_PIPS="m2crypto"` (we no longer use m2crypto).

Are we sure we don't use m2crypto anymore?  It is still being pulled in by various scripts in Keylime, for instance: 

https://github.com/keylime/keylime/blob/3fe81739efd1ec3e61f8ddf2f315ee42796f6145/keylime/tpm2.py#L45-L46

**Comment by lukehinds** [comment]
> > sorry, i see it now..your change has them in place. So its just a case of removing `PYTHON_PIPS="m2crypto"` (we no longer use m2crypto).
> 
> Are we sure we don't use m2crypto anymore? It is still being pulled in by various scripts in Keylime, for instance:
> 
> https://github.com/keylime/keylime/blob/3fe81739efd1ec3e61f8ddf2f315ee42796f6145/keylime/tpm2.py#L45-L46

doh! you completely right...I got mixed up with cryptodome! 

I will revert this change right away.

**Comment by jetwhiz** [comment]
> 
> 
> > > sorry, i see it now..your change has them in place. So its just a case of removing `PYTHON_PIPS="m2crypto"` (we no longer use m2crypto).
> > 
> > 
> > Are we sure we don't use m2crypto anymore? It is still being pulled in by various scripts in Keylime, for instance:
> > https://github.com/keylime/keylime/blob/3fe81739efd1ec3e61f8ddf2f315ee42796f6145/keylime/tpm2.py#L45-L46
> 
> I reacted to soon, its included as a dnf package @jetwhiz so we don't need a pip entry, see line 124:
> 
> https://github.com/keylime/keylime/blob/6068e1023de334d46b13661a093d2c5b31592f07/installer.sh#L120-L125

Yep, we still have it there for fedora, but it is not being installed for Ubuntu and CentOS/RHEL any longer.  Do we need to add them in via pkg managers?

**Pull request merged**
