### PR TITLE
Fix for ans1 unpackaged

### PR DESCRIPTION
**Pull request by lukehinds**
Resolves: #521

I am sure will need work still, but want to try this in CI and get some discussion going as this is a high priority to fix.

Note I remove, deep quote - no one is using this at all (I am certain), so I am happy to follow up and remove the rest.

Signed-off-by: Luke Hinds <lhinds@redhat.com>

### CODE REVIEW

**Comment by lukehinds** [comment]
@stefanberger

**Comment by dnoliver** [comment]
I am not 100% aware of what `ima_file_signing` does. Is that intended to check the IMA Signature of the measured files?

If that is the case, I have an objection for removing it :)

Starting with Fedora 34, the RPM contents will be signed for IMA. 

https://fedoraproject.org/wiki/Changes/Signed_RPM_Contents

Are you removing the capability to remotely verify those signatures?

**Comment by stefanberger** [comment]
I think the easiest would be to move the import of asn1 to the part that actually needs. No more DSA keys.

**Comment by lukehinds** [comment]
hold off on this one for https://github.com/keylime/keylime/pull/524 instead.

**Comment by mpeters** [comment]
Are we still going to go forward with this? It still has the feature of turning IMA signature support completely off, but is that desired?

**Comment by lukehinds** [comment]
I am happy to close this now.

**Pull request closed without merging**
