### PR TITLE
Revert "DO NOT MERGE, TEMPORARY COMMIT"

### PR DESCRIPTION
**Pull request by ansasaki**
This reverts commit 7671d60a4745b750986a0d4020b97a5ec2544195.

### CODE REVIEW

**Comment by ansasaki** [comment]
Tests should pass after https://github.com/RedHat-SP-Security/keylime-tests/pull/602 is merged.

**Comment by maugustosilva** [comment]
Will wait for this RedHat security PR to be merged then

**Comment by ansasaki** [comment]
We'll need another one merged before that, sorry about this: https://github.com/keylime/keylime/pull/1620

Basically, the images were not installing the latest keylime during build, but simply reusing the version installed during the base image build. The current images are using outdated Keylime, which is causing the testing failures.

If you could merge that first, it would help. Again, sorry about that.

**Review by maugustosilva — APPROVED** [review]

**Pull request merged**
