### PR TITLE
Fix broken tests

### PR DESCRIPTION
**Pull request by mpeters**
Fixing 2 tests of broken tests at once to get CI working again:

* Fix separate reg cv tests
* Fix botched fix of max_upload_size int conversion

### CODE REVIEW

**Comment by lukehinds** [comment]
Does this fix the tests that are failing?

**Comment by mpeters** [comment]
Yes, it should get CI back to normal

**Comment by lukehinds** [comment]
here is the build report, unfortunately this max upload size is still failing:

https://travis-ci.org/github/keylime/keylime/jobs/730337434#L396

**Comment by mpeters** [comment]
> here is the build report, unfortunately this max upload size is still failing:
> 
> https://travis-ci.org/github/keylime/keylime/jobs/730337434#L396

Yeah, my other PR fixes that. That one was held up by these failures, so I went to fix those first. Should they all be combined?

**Comment by lukehinds** [comment]
> > here is the build report, unfortunately this max upload size is still failing:
> > https://travis-ci.org/github/keylime/keylime/jobs/730337434#L396
> 
> Yeah, my other PR fixes that. That one was held up by these failures, so I went to fix those first. Should they all be combined?

sure, make another quick commit with your int fix and we should see CI pass as well then.

**Comment by mpeters** [comment]
Here: https://travis-ci.org/github/keylime/keylime/builds/730343055

Should I remove that fix to have them be separate commits or just leave them packaged as one?

**Comment by lukehinds** [comment]
I reckon we can just merge this one and close the other if that works for you?

**Review by lukehinds — APPROVED** [review]

**Pull request merged**
