### PR TITLE
Remove TPM 1.2 from CI/CD, installer and bundling scripts

### PR DESCRIPTION
**Pull request by stefanberger**
This PR removes TPM 1.2 support from CI/CD and the installer and bundling scripts.

### CODE REVIEW

**Comment by stefanberger** [comment]
I kept the `-m` option support to keep it compatible with existing scripts, though it's not clear whether such scripts exist elsewhere.

**Comment by mpeters** [comment]
@lukehinds when you get a chance can you review this? It's a continuation of the process you started to remove TPM 1.2 support

**Comment by maugustosilva** [comment]
LGTM

**Review by mpeters — APPROVED** [review]
lgtm

**Pull request merged**
