### PR TITLE
Remove Travis

### PR DESCRIPTION
**Pull request by lukehinds**
Resolves: #507 

Webhok already moved.

### CODE REVIEW

**Review by mbestavros — CHANGES_REQUESTED** [review]
@lukehinds You need to sign this off, but otherwise yes please!

**Comment by lukehinds** [comment]
I can't sign off unfortunately, did this in the github UI which you can't sign off with. I sometimes do this when I have a big patch underway and don't want to stash and mess around in git. I guess I should get out of this habit.

**Comment by mpeters** [comment]
Replaced by https://github.com/keylime/keylime/pull/541

**Comment by mpeters** [comment]
@lukehinds , no worries it's simple enough, I'll just submit a new PR for the same thing and we can close this one.

**Pull request closed without merging**
