### PR TITLE
codestyle: Enable check for undefined variables (E0602)

### PR DESCRIPTION
**Pull request by stefanberger**
This patch addresses the following issues.

$ make check
scripts/check_codestyle.sh
************* Module keylime.vtpm_manager
keylime/vtpm_manager.py:529:58: E0602: Undefined variable 'SafeDumper' (undefined-variable)
************* Module keylime.tenant_webapp
keylime/tenant_webapp.py:328:24: E0602: Undefined variable 'logging' (undefined-variable)
keylime/tenant_webapp.py:406:24: E0602: Undefined variable 'logging' (undefined-variable)
************* Module keylime.openstack
keylime/openstack.py:30:88: E0602: Undefined variable 'e' (undefined-variable)
************* Module test.oldtest
test/oldtest.py:728:34: E0602: Undefined variable 'file' (undefined-variable)

-------------------------------------------------------------------
Your code has been rated at 9.97/10 (previous run: 10.00/10, -0.03)

Note: file existed with python2 like this:

>>> f=open("/bin/bash")
>>> type(f)
<type 'file'>

With python3 it is like this:

>>> f=open("/bin/bash")
>>> type(f)
<class '_io.TextIOWrapper'>

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

### CODE REVIEW

**Review by mpeters — APPROVED** [review]
lgtm

**Review by mpeters — APPROVED** [review]
lgtm

**Comment by mpeters** [comment]
@stefanberger seems there are some conflicts with other stuff. If you can resolve those I can merge this.

**Comment by stefanberger** [comment]
rebased

**Pull request merged**
