### PR TITLE
Add more e2e tests to Packit CI

### PR DESCRIPTION
**Pull request by kkaarreell**

### CODE REVIEW

**Comment by kkaarreell** [comment]
> > I think it is a bug in keylime. I am observing this issue irregularly in scenarios involving DB.
> 
> Or maybe it is due to [sqlalchemy/alembic#982 (comment)](https://github.com/sqlalchemy/alembic/issues/982#event-5988865407) fixed in the mean time.

Actually not, I think that issue didn't impact F34.

**Comment by kkaarreell** [comment]
I have reported the verifier issue as https://github.com/keylime/keylime/issues/874

**Comment by THS-on** [comment]
This change is also includes in #889

**Comment by kkaarreell** [comment]
> This change is also included in #889

@THS-on , should we close this PR?

**Comment by THS-on** [comment]
yes.

**Pull request closed without merging**
