### PR TITLE
Allow graceful shutdown of the verifier

### PR DESCRIPTION
**Pull request by THS-on**
@kkaarreell noticed that the shutdown of the verifier results in an error. This should fix that.

### CODE REVIEW

**Review by mpeters — APPROVED** [review]

**Comment by THS-on** [comment]
The Fedora 34 test is failing and cannot see why this change should have an impact on the agent quote status and it passes on centos 9. @kkaarreell maybe a timing issue between adding the agent and checking the agent state?

**Comment by kkaarreell** [comment]
@THS-on could you reschedule tests by adding the above comment?

**Comment by kkaarreell** [comment]
That last failure is due to occasional error during TPM setup. I think you can ignore it, usually test rerun passes. I am not sure what is the culprit but it is not related to this PR.

**Pull request merged**
