### PR TITLE
Fix typo for config param listen_notifications

### PR DESCRIPTION
**Pull request by mpeters**
Fixes issue #867

Signed-off-by: Michael Peters <mpeters@redhat.com>

### CODE REVIEW

**Review by THS-on — APPROVED** [review]
The CI failure seems not to be related to this change because it only happens for one system, LGTM.

@kkaarreell the revocation action test seems flaky. Do you know if this is a timing issue or something related to zeromq?

**Comment by kkaarreell** [comment]
> @kkaarreell the revocation action test seems flaky. Do you know if this is a timing issue or something related to zeromq?

It is possible that it is a timing issue. I have never observed it before on a localhost test but I saw something like that on multi-host test. Did it failed just once? I think it should be possible to reschedule just that one failing test eventually from the Details page.

**Comment by THS-on** [comment]
> Did it failed just once? 

No it happens quite frequently, but goes away after a few retries. For example in https://github.com/keylime/keylime/pull/861 there were multiple tries necessary to get them all to pass.

**Comment by kkaarreell** [comment]
> > Did it failed just once?
> 
> No it happens quite frequently, but goes away after a few retries. For example in #861 there were multiple tries necessary to get them all to pass.

Should be addressed by https://github.com/RedHat-SP-Security/keylime-tests/pull/46

**Pull request merged**
