### PR TITLE
web_util: handle tls_dir default with cacerts correctly

### PR DESCRIPTION
**Pull request by THS-on**
Fixes: #1354

### CODE REVIEW

**Review by aplanas — APPROVED** [review]

**Review by sergio-correia — APPROVED** [review]

**Comment by THS-on** [comment]
I missed the case when the `tls_dir` is set to `generate`. This should now also work in that instance.

**Review by maugustosilva — APPROVED** [review]

**Comment by THS-on** [comment]
I've undid the change to `get_tls_options` because the handling there was already correct. Should be now ready to merge.

**Pull request merged**
