### PR TITLE
Fix the issue that tenant can't override verifier address from comman line

### PR DESCRIPTION
**Pull request by kaifeng**
Create verifier_base_url on demand.

Resolves: #447

### CODE REVIEW

**Comment by kaifeng** [comment]
I wonder if there is a mechanism to recheck the travis job, the failure doesn't seem related with the change and the log implies a build error.

**Comment by kaifeng** [comment]
> 
> 
> I wonder if there is a mechanism to recheck the travis job, the failure doesn't seem related with the change and the log implies a build error.

things turned out that the test is not consistent with code.

**Comment by maugustosilva** [comment]
I've tested it, and the very same bug persists. The `keylime_tenant` CLI is still ignoring the `-v` option (I actually don't see this CLI parameter being processed on the code).

**Comment by kaifeng** [comment]
> 
> 
> I've tested it, and the very same bug persists. The `keylime_tenant` CLI is still ignoring the `-v` option (I actually don't see this CLI parameter being processed on the code).

This is stange, the -v is processed here https://github.com/keylime/keylime/blob/master/keylime/tenant.py#L938-L939
Any idea why this change didn't work for you?

**Comment by kaifeng** [comment]
> 
> 
> > I've tested it, and the very same bug persists. The `keylime_tenant` CLI is still ignoring the `-v` option (I actually don't see this CLI parameter being processed on the code).
> 
> This is stange, the -v is processed here https://github.com/keylime/keylime/blob/master/keylime/tenant.py#L938-L939
> Any idea why this change didn't work for you?

Well, it appears we have naming issues here, cloudverifier_ip and verifier_ip are both used and easily get wrong..
Will push an update soon.

**Comment by maugustosilva** [comment]
Just tested it, and can confirm it is working now. My vote is to merge it as is.

**Review by mpeters — APPROVED** [review]
lgtm

**Pull request merged**
