### PR TITLE
Enable functional testing with Packit CI

### PR DESCRIPTION
**Pull request by kkaarreell**
Enables functional testing using Packit/TFT CI on tests from
https://github.com/RedHat-SP-Security/keylime-tests

### CODE REVIEW

**Comment by kkaarreell** [comment]
@mpeters @sergio-correia @mbestavros FYI

**Comment by kkaarreell** [comment]
Tests seems to be running properly. 

Currently, there is just one functional test enabled doing the basic attestation on localhost using emulated TPM and keylime IMA emulator. I plan to enable additional tests once they are implemented and stable.

Also, please be aware that due to a bug in the Packit/TFT service tests are listed in a wrong order in the log (execution follows the proper order as timestamps suggest).

**Comment by sopos** [comment]
nice

**Comment by kkaarreell** [comment]
I don't know why test is failing on Rawhide but I can see it has newer tpm2-tss version (tpm2-tss-3.1.0-4.fc36). Maybe there is another regression in that package.

**Comment by kkaarreell** [comment]
Still don't know what is the problem with Rawhide but after downgrading tpm2-tss to a package from F35 the test passes.

**Review by mpeters — APPROVED** [review]

**Pull request merged**
