### PR TITLE
Improvments to Measured Boot

### PR DESCRIPTION
**Pull request by THS-on**
- elchecking: add handling for EV_EFI_PLATFORM_FIRMWARE_BLOB2
- elchecking/example: workaround empty PK, KEK, db and dbx

Fixes the issue observed in https://github.com/keylime/keylime/issues/1617

### CODE REVIEW

**Comment by ansasaki** [comment]
@kkaarreell Could you please verify that this fixes the issue you saw on RHEL-9?

**Comment by kkaarreell** [comment]
> @kkaarreell Could you please verify that this fixes the issue you saw on RHEL-9?

It does for a system with UEFI. Tomorrow, I will also check SecureBoot enabled system.

**Comment by kkaarreell** [comment]
> > @kkaarreell Could you please verify that this fixes the issue you saw on RHEL-9?
> 
> It does for a system with UEFI. Tomorrow, I will also check SecureBoot enabled system.

It does, I think this is OK to merge.

**Review by ansasaki — APPROVED** [review]
Code-wise it LGTM. From Karel's comment, it fixes the mentioned issue.

**Pull request merged**
