### PR TITLE
Fix user_data_encrypt to UTF8 decode before print

### PR DESCRIPTION
**Pull request by mpeters**
Patch from Ilhan Gurel (ilhan.gurel@ericsson.com)

Signed-off-by: Michael Peters <mpeters@redhat.com>

### CODE REVIEW

**Comment by stefanberger** [comment]
Is this fixing an issue or fixing a 'potential' issue?

**Comment by mpeters** [comment]
It's fixing a real issue that Ilhan hit, but I don't know the details of how he triggered. I'll see if I can get those from him before merging this

**Comment by stefanberger** [comment]
It would be good if the issue was described in the commit.

**Comment by igurel** [comment]
Reproducible on Ubuntu 20.04 (Python 3.8.5)

$ keylime_userdata_encrypt secret.bin
Writing keys to content_keys.txt
Traceback (most recent call last):
  File "/usr/local/bin/keylime_userdata_encrypt", line 8, in <module>
    sys.exit(main())
  File "/home/ens/.local/lib/python3.8/site-packages/keylime/cmd/user_data_encrypt.py", line 53, in main
    f.write(base64.b64encode(ret['k']))
TypeError: write() argument must be str, not bytes

**Comment by stefanberger** [comment]
I never used this tool before, but yes, I see that now also on 3.9.2. I think this backtrace should go into the patch description.

**Comment by mpeters** [comment]
Commit message updated with the backtrace

**Comment by stefanberger** [comment]
LGTM.

I wonder whether python has changed so that this doesn't work anymore?

**Pull request merged**
