### PR TITLE
Remove restful test to restore run_local.sh

### PR DESCRIPTION
**Pull request by THS-on**
As discussed on the last meeting, we just remove the restful test to make running the unit tests locally easier. `.ci/run_local.sh` now works and runs in a reasonable time.
It also renames the files in the config test to make agent removal easier later on.

### CODE REVIEW

**Comment by THS-on** [comment]
The e2e tests, cover pretty much everything that the restful test covers and is way simpler to run.

**Comment by aplanas** [comment]
> The e2e tests, cover pretty much everything that the restful test covers and is way simpler to run.

Naive question: with e2e you mean the packit tests? How can those be executed locally?

**Comment by THS-on** [comment]
@aplanas yes I mean the packit tests. You can run them locally, the documentation for that can be found here: https://github.com/RedHat-SP-Security/keylime-tests/blob/main/TESTING.md

**Comment by aplanas** [comment]
> @aplanas yes I mean the packit tests. You can run them locally, the documentation for that can be found here: https://github.com/RedHat-SP-Security/keylime-tests/blob/main/TESTING.md

Oh thanks. Seems that tmt is not frequently found outside RH. I will make it available in openSUSE too.

**Comment by THS-on** [comment]
I would like to get this in, so that I can remove the agent more easily. I will look into adding back pure REST unit tests that not require the agent running, after the removal is complete.

**Review by aplanas — APPROVED** [review]

**Review by mpeters — APPROVED** [review]

**Review by sergio-correia — APPROVED** [review]

**Pull request merged**
