### PR TITLE
Bump version number to 6.5.3

### PR DESCRIPTION
**Pull request by mpeters**
Signed-off-by: Michael Peters <mpeters@redhat.com>

### CODE REVIEW

**Comment by mpeters** [comment]
At this point we could just skip to 6.6.0, but wanted to throw this out just in case a final 6.5.x was wanted.

**Review by THS-on — APPROVED** [review]
Let us make a 6.5.3 now and then when #1147 is merged a 6.6.0

**Comment by maugustosilva** [comment]
Are you guys ok including #1258 on this minor release? I believe I have addressed all the comments there.

**Comment by mpeters** [comment]
> Are you guys ok including #1258 on this minor release? I believe I have addressed all the comments there.

There's still a comment from Stefan about `agentAttestState` that seems unresolved.

**Pull request merged**
