### PR TITLE
New webapp GUI

### PR DESCRIPTION
**Pull request by MartinMa28**
Thanks for [Chencheng](https://github.com/Gcccccccc) and [Fengqi](https://github.com/FengqiQiao), in the new front-end GUI, we have the following features:
1. Have a pie chart to show the overview of the system.
2. The selected agents are paginated.
3. The requests are staggered into smaller batches to avoid using larger intervals when more and more agents are registered. Within each interval, only a batch of requests is sent to webapp back-end so that the throughput is manageable.
4. Use JS Fetch API in pie chart and pagination. The remaining legacy code still uses XMLHttpRequest API.

The way of HTML rendering is not changed because it requires significant changes in keylime's building process.

Issue:
 #636 

webapp_failed
webapp_get_quote
webapp_registered

Signed-off-by: MartinMa28 <1135485226@qq.com>

### CODE REVIEW

**Comment by lukehinds** [comment]
That's really cool, thank you authors.

This shows there is an interest in a GUI. I wonder if its time we restocked work on https://github.com/keylime/enhancements/blob/master/7_multi-tenancy.md

https://github.com/keylime/keylime/pull/309

This way we could add an auth system to the front of the webUI? Would you folks be interested in working on the front end aspects if a token system is on the backend?

**Comment by MartinMa28** [comment]
> That's really cool, thank you authors.
> 
> This shows there is an interest in a GUI. I wonder if its time we restocked work on https://github.com/keylime/enhancements/blob/master/7_multi-tenancy.md
> 
> #309
> 
> This way we could add an auth system to the front of the webUI? Would you folks be interested in working on the front end aspects if a token system is on the backend?

Thanks for your invitation. For me, I am interested in the multi-tenancy feature, but I am afraid that we cannot spend so much time on keylime in the near future. We will start working full-time/internship this May. So, if multi-tenancy is something really masters at the moment, probably we cannot get it done in one or two months. If it's more of an enhancement to keylime open source community, I would love to look into it.

**Comment by MartinMa28** [comment]
> This looks awesome, great job everyone!
> 
> Regarding the more long-term vision, as we eventually move over to using something like tornado templates as you mention, is it possible to also move over to a more open source friendly charts implementation (such as https://github.com/chartjs/Chart.js)?
> 
> The Google-based charts require a persistent connection to the internet (which might not always be available for Keylime running on a local intranet with no connectivity to the outside). It is also a violation of Google's TOS to download their charts source code and host it locally.

Sure, we have no problem moving to Chart.js. We might need a few more days to refactor since we are in the middle of something. By next Tuesday or Wednesday, the refactoring should be done.

**Comment by mpeters** [comment]
@MartinMa28 any news on the refactor to Chart.js?

**Comment by mpeters** [comment]
@MartinMa28, @Gcccccccc and @FengqiQiao: any news on the refactor to Chart.js?

**Comment by lukehinds** [comment]
Its almost a year this has been left hanging, so I will close (it can always be re-opened if OP wishes to still work on it).

**Pull request closed without merging**
