### PR TITLE
ima: Implement ima-buf validator and validate keys on keyrings

### PR DESCRIPTION
**Pull request by stefanberger**
Implement the ima-buf validator and check whether the data part of the
ima-buf log entry is a keyring to check it against a keyring entry. Use the
'keyrings' selector for selecting the 'keyrings' map in the allowlist when
checking the keyring name using the ima-ng validator.

### CODE REVIEW

**Comment by stefanberger** [comment]
Todo: test case

**Comment by THS-on** [comment]
I've tested it on my small test setup and it seems to work as intended. 

If we change the allowlist format `ALLOWLIST_CURRENT_VERSION` should be probably increased.
https://github.com/keylime/keylime/blob/35d0ae1df571e2719e9338f8ea406d0ed2b4cc6e/keylime/ima.py#L27

When this gets merged documentation for it should be added to keylime-docs.

**Comment by stefanberger** [comment]
> 
> 
> I've tested it on my small test setup and it seems to work as intended.
> 
> If we change the allowlist format `ALLOWLIST_CURRENT_VERSION` should be probably increased.
Ah, right.
> 
> https://github.com/keylime/keylime/blob/35d0ae1df571e2719e9338f8ea406d0ed2b4cc6e/keylime/ima.py#L27
> 
> When this gets merged documentation for it should be added to keylime-docs.

yes.

**Comment by maugustosilva** [comment]
Please rebase so I can properly test it.

**Comment by stefanberger** [comment]
Rebased. I took out one fix that I am going post separately.

**Review by maugustosilva — APPROVED** [review]

**Comment by maugustosilva** [comment]
LGTM

**Review by mpeters — APPROVED** [review]

**Pull request merged**
