### PR TITLE
tpm_util: Add the BSD license to the file due to functions from TPM 2 code

### PR DESCRIPTION
**Pull request by stefanberger**
The functions to implement TPM2's MakeCredential were taken from the TPM 2 reference implementation that requires that the license and notices be kept but allows for distribution and creation of detrivative works.

### CODE REVIEW

**Comment by mpeters** [comment]
@ansasaki @sergio-correia or @aplanas Do you know of any problems including a copyright like this might have on packaging/distribution?

**Comment by aplanas** [comment]
> @ansasaki @sergio-correia or @aplanas Do you know of any problems including a copyright like this might have on packaging/distribution?

Ah thanks a lot for pinging.

I am not sure to recognize the license, is this "BSD-3-Clause"? Can this coexist with the current "Apache-2.0" that is the one in Keylime?

**Comment by ansasaki** [comment]
> @ansasaki @sergio-correia or @aplanas Do you know of any problems including a copyright like this might have on packaging/distribution?

As @aplanas mentioned above, the question is if this license can coexist with the current used licensing.

If this is not based on a known good license, it will also requires some extra work and special analysis from legal to check if we can include it as part of products and distributions. For Fedora, we would have to also work to include it in https://spdx.dev/ licenses list.

In any case, if we took part of the code from somewhere that has that licensing requirements, we have to abide.

**Comment by stefanberger** [comment]
Microsoft reference implementation uses BSD, so changed it to that as well.

**Comment by aplanas** [comment]
LGTM, IIUC the new package license will be "Apache-2.0 AND BSD-3-Clause", and that should be OK (IANAL)?

**Comment by stefanberger** [comment]
> LGTM, IIUC the new package license will be "Apache-2.0 AND BSD-3-Clause", and that should be OK (IANAL)?

I think so.

**Review by aplanas — APPROVED** [review]

**Pull request merged**
