### PR TITLE
Move lint check to a job

### PR DESCRIPTION
**Pull request by kaifeng**
Move pylint check to a job so it doesn't block
functional tests.

### CODE REVIEW

**Comment by kaifeng** [comment]
pylint is raising issues that were exposed before, not sure what is happening because the version is still 2.6.0.

**Comment by kaifeng** [comment]
> 
> 
> pylint is raising issues that were not exposed before, not sure what is happening because the version is still 2.6.0.

It was introduced from another patch that was passed checking before W0707 enabled.

**Comment by mpeters** [comment]
> It was introduced from another patch that was passed checking before W0707 enabled.

Ah, so because there wasn't a conflict a previously passing PR merged that caused this new failure after it was rebased in GH? I guess that's an argument for not rebasing in GH but on the actual commit to retrigger CI... but it is very convenient.

**Review by mpeters — APPROVED** [review]
lgtm

**Pull request merged**
