### PR TITLE
Promote Kaifeng Wang to MAINTAINER

### PR DESCRIPTION
**Pull request by lukehinds**
I would like to propose that Kaifeng Wang be promoted to maintainer.

Kaifeng has contributed some significant PR's to the project and
refactored large amounts of the code base to make the project layout
better organised. Kaifeng also helps out reviewing others code.

Any current MAINTAINERS are welcome to +1/-1. If a positive ratio
stands in one week from now (10/12/202) I will merge this PR.

Signed-off-by: Luke Hinds <lhinds@redhat.com>

### CODE REVIEW

**Comment by lukehinds** [comment]
tagging @maugustosilva (not available in reviewers, so we need to look into that

**Comment by ashcrow** [comment]
+1

**Comment by axelsimon** [comment]
No objections from me.
+1

**Review by axelsimon — APPROVED** [review]

**Review by mpeters — APPROVED** [review]
lgtm, welcome aboard @kaifeng !

**Review by amylily1011 — APPROVED** [review]

**Review by ashcrow — APPROVED** [review]

**Review by font — APPROVED** [review]
+1

**Review by nabilschear — APPROVED** [review]

**Review by jetwhiz — APPROVED** [review]

**Comment by lukehinds** [comment]
Approved, welcome on board @kaifeng

**Comment by kaifeng** [comment]
Thanks everyone for the trust o/

**Pull request merged**
