### PR TITLE
Add support for keylime_webapp service to read intervals from keylime.conf

### PR DESCRIPTION
**Pull request by FengqiQiao**
This PR is an implementation for #599

### CODE REVIEW

**Comment by maugustosilva** [comment]
Looks good, LGTM

**Review by mpeters — APPROVED** [review]
lgtm

**Comment by dcmiddle** [comment]
@mpeters @FengqiQiao 
Not sure if you require sign-offs, but I just happened to notice this one seems to accidentally have been from an unconfigured git client..
`Signed-off-by: root <root@localhost.localdomain>`
As it's the head commit you could maybe still rebase it w/o too much difficulty. If you care. :)

**Comment by mpeters** [comment]
Sorry, I didn't notice this bad signature. We do require sign-offs going forward so I'm not totally sure of the right way to correct this. We don't want to amend the head because it's now published and any changes we make will break others checkouts. I'm fine making changes to git branches/forks that aren't the primary main branch of a project, but once it's out there like this, it's kind of permanent.

@lukehinds and/or @axelsimon do you have any thoughts on the best way to fix this? If nothing else, maybe the DCO bot should be updated to be able to catch these since `root@localhost.localdomain` is never a person that can sign off on where the code came from.

**Comment by FengqiQiao** [comment]
So sorry about that, my bad. `root@localhost.localdomain` is actually me. 
In order to get a clean dev environment, I created a new VM and worked on this PR under root user. However, I forgot to set up git using `git config --global user.name` and `git config --global user.email`. So when I pushed the commit, it resulted in the bad signature.

**Comment by dcmiddle** [comment]
@mpeters I think you can revert which will lay down a new commit. @FengqiQiao can then amend their commit, fetch upstream, and then locally rebase on top of the new head and then push. The offending commit will still be in history but will be immediately adjacent to the reversion and the new commit. 
Probably other options too.

**Pull request merged**
