### PR TITLE
Bump required packaging module version to 20.0

### PR DESCRIPTION
**Pull request by kkaarreell**
We are already consuming attributes such as 'minor'
and 'major' introduced by this version in api_version.py.

Signed-off-by: Karel Srot <ksrot@redhat.com>

### CODE REVIEW

**Review by THS-on — APPROVED** [review]

**Review by sergio-correia — APPROVED** [review]

**Comment by kkaarreell** [comment]
test_restful.py is unstable on CS8, seems that TPM restarting fails frequently. Maybe we should exclude this test on CS8.

**Comment by kkaarreell** [comment]
I think there are some packaging related issue with the Rawhide image used in CI. I cannot reproduce it myself though, it must be related to the internal Testing farm repo.

**Comment by kkaarreell** [comment]
JFTR, https://koji.fedoraproject.org/koji/buildinfo?buildID=1944200 is responsible for broken deps in Rawhide.

**Comment by kkaarreell** [comment]
> test_restful.py is unstable on CS8, seems that TPM restarting fails frequently. Maybe we should exclude this test on CS8.

Done.

**Review by mpeters — APPROVED** [review]

**Pull request merged**
