### PR TITLE
Some notes for how to setup keylime tpm 1.2 development on a mac.

### PR DESCRIPTION
**Pull request by nabilschear**
Can someone with a mac see if this works as is?  all of my machines are already installed.

### CODE REVIEW

**Comment by lukehinds** [comment]
I can't help there @nabilschear , I don't have a mac.

If possible though, could you instead add this a PR to https://github.com/keylime/keylime-docs

**Comment by nabilschear** [comment]
yes, i'll move this over to the docs repo

**Comment by nabilschear** [comment]
dumb question: how do i build the keylime-docs stuff into html so i can check my formatting?

**Comment by lukehinds** [comment]
Not a dumb question at all!

`pip install -r requirements.txt`

`cd docs`

`make html`

This will report any stuff like formatting errors.

You then go into `_build/html` and the rendered files will be there

```
 ls _build/html                                                                                                                                                                      
404.html  developers.html  genindex.html  http-routingtable.html  _images  index.html  installation.html  objects.inv  rest_apis.html  search.html  searchindex.js  security.html  _sources  _static  user_guide  user_guide.html
```

Also when you make the pull request, readthedocs will do the same as the above and report on build status.

**Comment by nabilschear** [comment]
moving this to keylime-docs repo

**Pull request closed without merging**
