### PR TITLE
Add signature verification support for local and remote IMA signature verification keys

### PR DESCRIPTION
**Pull request by stefanberger**
This PR adds signature verification support for local and remote IMA signature verification keys.

### CODE REVIEW

**Comment by stefanberger** [comment]
@puiterwijk @mpeters So this PR is now the equivalent to the recent extensions for signed allowlists. I make the same assumptions that a GPG key will be used for verification but I don't support checksums. Do you have any comments? 

There's more explanation on the 3rd patch on how to use the options.

**Comment by stefanberger** [comment]
@lukehinds Do you have any comments about this? Are AllowList URLs already available?

**Comment by lukehinds** [comment]
> @lukehinds Do you have any comments about this? Are AllowList URLs already available?

@mpeters might know, he did that patch?

**Review by mpeters — APPROVED** [review]
lgtm, appreciate the gpg refactoring/reuse

**Comment by mpeters** [comment]
@stefanberger this looks good to me as it extends a pattern we're already using into other things. Let me know what else you have left to move out of WIP state.

**Comment by stefanberger** [comment]
@mpeters For the remote allow lists you require a checksum or signature. I don't currently require a signature on a remote key, but should I make this a requirement?

**Comment by mpeters** [comment]
That's a good question. I wanted to default to requiring one or the other just to get people in the habit of doing something more securely, but I don't have a firm stance either way.

**Comment by stefanberger** [comment]
I will leave it as it is for now and may come back later to enforce signatures, especially once they exist.

**Comment by maugustosilva** [comment]
@mpeters LGTM, I just tested it on my end-to-end CI successfully

**Pull request merged**
