### PR TITLE
Misc fixes for keylime-policy

### PR DESCRIPTION
**Pull request by sergio-correia**
- fix help for "keylime-policy sign" verb
- check for valid cert file when using x509 backend (sign)
- use Certificate() from models.base to validate certs
- exit with status 1 when the commands failed
-  improve error handling when provided a bad key (sign)

### CODE REVIEW

**Comment by kkaarreell** [comment]
@sergio-correia Hi, could you try to re-run tests? I think there was some infra issue that should be done now.

**Comment by sergio-correia** [comment]
> @sergio-correia Hi, could you try to re-run tests? I think there was some infra issue that should be done now.

Sure thing

**Review by ansasaki — APPROVED** [review]
The failure in Fedora-41 is unrelated and caused by https://bugzilla.redhat.com/show_bug.cgi?id=2326535

**Pull request merged**
