### PR TITLE
IMA: Remove DSA keys since they require python3-asn1

### PR DESCRIPTION
**Pull request by stefanberger**
The asn1 python module may not be widely available and DSA keys may not
be used frequently, so let's just remove the support for those types of
keys.

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

### CODE REVIEW

**Comment by lukehinds** [comment]
I will offline test this first thing early tomorrow (GMT).

**Review by mpeters — APPROVED** [review]
This looks good to me but I'll hold off on merging until after @lukehinds finishing his testing

**Comment by lukehinds** [comment]
I tested generic IMA measurements and this seems to work well (alongside everything starting)

image

**Review by lukehinds — APPROVED** [review]

**Comment by stefanberger** [comment]
THANK YOU!

**Pull request merged**
