### PR TITLE
Add pyright checks to CI/CD

### PR DESCRIPTION
**Pull request by stefanberger**
This PR adds pyright checks to CI/CD. It adds support for pyright to `make check` using a script scripts/check_static that builds a llist of python files and filters out those that are not clean for pyright.

### CODE REVIEW

**Comment by stefanberger** [comment]
@mdrocco I don't mind closing this PR. However, I think we should have pyright checks asap on those files that pass the checks. This PR adds duplicates with what you have already in `pyproject.toml` to some degree except that it filters out any files that don't pass.

**Comment by mdrocco** [comment]
of course I like this PR, I think type-checking should be part of the static analysis performed by CI. My only concern is about that list of files in `check_static.sh`, as we already specify the scope of `pyright` in `pyproject.toml`.

**Comment by stefanberger** [comment]
> of course I like this PR, I think type-checking should be part of the static analysis performed by CI. My only concern is about that list of files in `check_static.sh`, as we already specify the scope of `pyright` in `pyproject.toml`, I would rather populate that file with any exclusion we need.

Let me do this then and I will re-send this PR.

**Review by mdrocco — APPROVED** [review]

**Comment by stefanberger** [comment]
Looks like it ran:
```
* Install prebuilt node (19.1.0) ..... done.
No configuration file found.
pyproject.toml file found at /__w/keylime/keylime.
Loading pyproject.toml file at /__w/keylime/keylime/pyproject.toml
Assuming Python version 3.9
Assuming Python platform Linux
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
stubPath /__w/keylime/keylime/typings is not a valid directory.
Searching for source files
Found 111 source files
pyright 1.1.280
0 errors, 0 warnings, 0 informations 
Completed in 9.63sec
```

**Comment by mdrocco** [comment]
Once merged, I will take care of removing "fixed" files as part of #1180.

**Comment by mdrocco** [comment]
Do we have a mechanism to democratically vote for PR precedence? :) I would like to see this one merged as soon as possible, as at least two other PRs would benefit from it.

**Comment by stefanberger** [comment]
> Do we have a mechanism to democratically vote for PR precedence? :) I would like to see this one merged as soon as possible, as at least two other PRs would benefit from it.

You have my vote. Maybe @maugustosilva approves it and can merge it or we wait until tomorrow...

**Review by THS-on — APPROVED** [review]
LGTM. I verified that  CI with pyright ran successfully, so can we drop the last commit before merging?

**Comment by stefanberger** [comment]
> LGTM. I verified that CI with pyright ran successfully, so can we drop the last commit before merging?

Dropped.

**Pull request merged**
