### PR TITLE
registrar: Detect IPv6 addresses to bind to and set address_family

### PR DESCRIPTION
**Pull request by stefanberger**
Set self.address_family to socket.AF_INET6 if the provided IP address to bind to is an IPv6 address.

Resolves: Issue #1315

### CODE REVIEW

**Comment by aplanas** [comment]
This should fix one of the tests: https://github.com/keylime/keylime/pull/1348

**Review by aplanas — APPROVED** [review]
One test will be fixed in a different commit, so after you fix the linter one this can be merged.

**Comment by stefanberger** [comment]
> One test will be fixed in a different commit, so after you fix the linter one this can be merged.

We seem to have test failures now related to attestation...

**Review by aplanas — APPROVED** [review]

**Review by sergio-correia — APPROVED** [review]

**Pull request merged**
