### PR TITLE
Monthly release (7.8.0)

### PR DESCRIPTION
**Pull request by maugustosilva**

### CODE REVIEW

**Comment by THS-on** [comment]
@ansasaki is everything ok with the versioning of the configuration for this release?

**Comment by ansasaki** [comment]
Wait, do not merge this right now: maybe it added incompatibility with python 3.6

I'll investigate more and will report back.

**Comment by ansasaki** [comment]
@maugustosilva Sorry, apparently it was a false alarm.  I think you can proceed with the new release.

The problem in my case was an older `python-asn1-modules` which is missing the newly used `rfc4108`. Anyway, we should implement compatibility tests with a matrix of supported python versions and include in the CI.

About bumping the minimum python version, what are the benefits?

**Comment by maugustosilva** [comment]
@ansasaki Ok, I will leave the discussion about bumping the minimum python version for a future release, we are (well, I am :-) ) "late" with the release as is. Thanks.

**Comment by maugustosilva** [comment]
Just need an approval from someone now @mpeters @THS-on @stefanberger @aplanas @sergio-correia @ansasaki

**Review by aplanas — APPROVED** [review]

**Pull request merged**
