### PR TITLE
Verifier talk to each other

### PR DESCRIPTION
**Pull request by cjustacoder**
Try to implement the communication between two Verifier. Only focus on tornado part. A simple helloworld try for communication, not involve actual functions or interfaces.

Based on existing 'tornado', adding URL and handler correspond to GET request. Verifier communicate with each other using GET. Tenant verifier will send a GET request(using python requests package) before entering tornadoIOLoop. The rest of changes are comments which help me understand the code.

Resolves: #195

### CODE REVIEW

**Comment by nabilschear** [comment]
@cjustacoder it looks like you're mixing the existing non-blocking event-based approach for servicing requests from tenants with the blocking requests library.  Take a look at how this function does things.  https://github.com/keylime/keylime/blob/e2bfff7b1ebcaef9b3dec7d840f18133684e84bf/keylime/cloud_verifier_tornado.py#L295 Since you're operating in the tornado async world, you have to issue get requests to talk to others using the same mechanisms.  I'm also not sure about adding a totally different handler for this feature since all the state management and other stuff is already built in the other handler (see `process_agent`) could this be implemented by adding more operational states and moving through?

**Comment by nabilschear** [comment]
another thought, it would be great if the verifier essentially had a very similar rest interface as the agent.  So when the first verifier talks to the provider verifier, it uses the similar uris and other info.  It all depends on whether the merkle tree data is going to be kept and maintained.

**Comment by cjustacoder** [comment]
Thanks a lot, Nabil@nabilschear! I will dig into this and try to figure it out.

**Comment by cjustacoder** [comment]
Hi Nabil, @nabilschear. I'm still trying to dig the code. There is something I don't understand. 

I try to figure out the workflow so I print out each steps when runs the program, and below is my out put. 
```
[root@localhost keylime]# python3 cloud_verifier_tornado.py 
Using config file /etc/keylime.conf
Enter your identity: provider or tenant: provider
2019-10-24 16:24:09.376 - keylime.cloudverifier - INFO - no agent now(testing)
2019-10-24 16:24:09.376 - keylime.cloudverifier - INFO - Starting Cloud Verifier (tornado) on port 8881, use <Ctrl-C> to stop
2019-10-24 16:24:09.377 - keylime.cloudverifier_common - INFO - Setting up TLS...
2019-10-24 16:24:09.378 - keylime.cloudverifier_common - INFO - Existing CA certificate found in /var/lib/keylime/cv_ca, not generating a new one
2019-10-24 16:24:09.380 - keylime.cloudverifier - INFO - Starting service for revocation notifications on port 8992
entering the loop
entering the loop
get a post
/agents/D432FBB3-D2F1-4A97-9EF7-75BD81C00000
process_agent
1
invoke_get_quote
http://127.0.0.1:9002/quotes/integrity?nonce=SACTsgsJOIyQ9xcWQIAF&mask=0x408000&vmask=0x808000&partial=0
2019-10-24 16:24:25.072 - keylime.cloudverifier - INFO - POST returning 200 response for adding agent id: D432FBB3-D2F1-4A97-9EF7-75BD81C00000
on_get_quote_response
2019-10-24 16:24:25.422 - keylime.cloudverifier - INFO - content of quote
```

It seems like after entering `tornado.ioloop.IOLoop.instance().start()`https://github.com/keylime/keylime/blob/e2bfff7b1ebcaef9b3dec7d840f18133684e84bf/keylime/cloud_verifier_tornado.py#L513, the tornado keeps idling until it receives a POST from agent. Then the verifier invokes a `process agent` function, but I didn't see any invoke from the POST handler. https://github.com/keylime/keylime/blob/e2bfff7b1ebcaef9b3dec7d840f18133684e84bf/keylime/cloud_verifier_tornado.py#L176-L239

So I'm wondering who invoke the 'process_agent' in this process? Thanks a lot!

**Comment by cjustacoder** [comment]
@nabilschear @lukehinds, I have updated some changes, still couldn't get through. Can you please help me to have a look? Thanks a lot!

**Comment by nabilschear** [comment]
process_agent gets called here in post https://github.com/cjustacoder/keylime/blob/f2bb598113bfd263153e6f66b811167cbf8b8250/keylime/cloud_verifier_tornado.py#L269

there's a little state machine that agents go through that is driven by it's operational_state value.  all of the state transitions happen in `process_agent` .  So you should be able to see old state new state transitions all in that function.

**Comment by nabilschear** [comment]
I wasn't able to figure out what was going wrong with this (i only tried a little).  So, i spent a little bit of time to figure out the basic scaffolding for what you'll want to do to do it right.  See #194 for the code @cjustacoder

**Pull request closed without merging**
