### PR TITLE
Major overhaul of allowlist functionality

### PR DESCRIPTION
**Pull request by mbestavros**
This PR implements a few significant improvements to Keylime's allowlist functionality, notably:

- The partially-complete Allowlists API on the verifier has been finished and is now fully functional with `create`, `retrieve`, and `delete` actions.
- Allowlists are now stored in their own, separate database - instead of `VerifierMain`, they now live in the as-yet unused `VerifierAllowlist` database.
- There have been major changes to the `add` command for adding agents to accommodate the new database arrangement - now, you can add an agent without providing an allowlist file if an allowlist was previously uploaded using the Allowlists API.
  - At the same time, existing functionality has been preserved: providing an allowlist file with the `add` command will still store the allowlist as before.
- Refactored allowlist processing code to perform disk loading and further processing separately from each other
- Deferred allowlist processing/reformatting to the verifier, which allows for verifier-side signature validation

TODO:

- Ensure namespaces are consistent
- At present, Keylime still stores the edited/processed allowlist artifact, and not the original as provided by the user on the tenant.
- Some further database work is needed, and it's possible some migrations will need to be written.
- Some tests are broken by these changes that will need to be fixed.
- General code cleanup

Signed-off-by: Mark Bestavros <mbestavr@redhat.com>

### CODE REVIEW

**Comment by lukehinds** [comment]
nice work Mark. 

What's the thinking behind a separate DB?

**Comment by mpeters** [comment]
A separate DB table is also necessary for the 1-to-many relationship for multi-allowlist. That's a separate feature, but it's something we'll need eventually so if it works as a design for this feature then lets go with it.

**Comment by THS-on** [comment]
@mbestavros thanks for clarifying.

> I haven't implemented any functionality to remove uploaded allowlists when an agent is deleted - in this draft of the code, if you provide an allowlist file, you must also provide an allowlist name, and it will persist after the agent is deleted. This can change, of course.

I would say if there is now name provided generate a automatic one and remove the entry after the agent is removed, otherwise persist it.

**Comment by lukehinds** [comment]
do you want to rebase this @mbestavros ?

**Pull request closed without merging**
