### PR TITLE
Refactored IP address and Port in the configration file

### PR DESCRIPTION
**Pull request by rajdroid**
Currently, the layout of the configuration file is clumsy. This
change try to group logical items together, so that it make sense.

Resolves: #247

### CODE REVIEW

**Comment by rajdroid** [comment]
Hi @lukehinds could you please review these changes. And I was not able to work on '-c delete' bug that is mentioned because my VM is not able to connect to TPM, so I can't test. I will work on that issue after I resolve my setup.

**Comment by lukehinds** [comment]
Hi Raj,

Just travelling back home, will take a look tomorrow

For tpm, try..

# tpm_serverd
# systemctl restart tpm2-abrmd

It might be underscore if that fails... tpm2_abrmd

Test with # tpm2_pcrread

**Comment by rajdroid** [comment]
Sure @lukehinds whenever you get time. And I'll try your suggested method to resolve the issue.

**Comment by rajdroid** [comment]
Hi @lukehinds, I tried tpm2_pcrread, but it fails as well. Interestingly, I don't find the TPM device in the VM. 
`% ll /dev/ | grep tpm`

**Comment by jetwhiz** [comment]
Hi @rajdroid -- if you're doing this in a VM (and with the tpm2 emulator) then you will need to have tpm2_abrmd using mssim (the TPM will not be available as a hardware device). See: https://github.com/keylime/keylime#tpm-20-resource-manager for how to make this change.

**Comment by rajdroid** [comment]
Hi @jetwhiz, Thanks, I'll try the shared resource, but I am using this resource (https://github.com/keylime/ansible-keylime-tpm-emulator) to provision VM, so I believe this should automatically be handled during provisioning.

**Comment by lukehinds** [comment]
Another option while we fix this for you @rajdroid is to run within a container. Check out https://keylime-docs.readthedocs.io/en/latest/developers.html#docker-development-environment

This will pull down the images we use in CI and mount your local repository.

I would perhaps make a tweak and remove these lines:

```
docker stop "$(cat ${container_id})"
docker rm "$(cat ${container_id})"
```

You could then run `docker ps -a` and get the ID of the container and `docker attach $ID`, you should then be in a fully working environment. Note though that IMA won't work in this context as IMA is not namespaced yet, we need this work to complete:

http://kernsec.org/wiki/index.php/IMA_Namespacing_design_considerations

However http ports and running the keylime services should be fine.

**Comment by lukehinds** [comment]
oh, and change 

```
tpm20tag="v301"
```

to

```
tpm20tag="v501"
```

**Comment by rajdroid** [comment]
Thanks @lukehinds, let me try that

**Comment by rajdroid** [comment]
Hi @lukehinds, docker way does worked, but I'm debugging why tpm2_abrmd is not working.

**Pull request merged**
