### PR TITLE
park the howto on freebsd in docs

### PR DESCRIPTION
**Pull request by nabilschear**
A while back i wrote up some docs on getting keylime running on freebsd.  I thought it would be good to have these docs in the docs folder in case anyone ever wants to pick this up again.

related to https://github.com/keylime/keylime/issues/254

### CODE REVIEW

**Comment by lukehinds** [comment]
this is great, but we should try to use keylime-docs now instead of docs

**Comment by nabilschear** [comment]
Considering this is kinda unofficial documentation, think it's ok going here?  I can certainly mkdocs it.

**Comment by ashcrow** [comment]
Does anyone have feedback/an answer on @nabilschear's question?

**Comment by lukehinds** [comment]
I guess it could go in /doc. I would just like to see our offical docs getting more content. There is an installation section, but its not dist specific (its based on ansible / installer.sh), so I guess just having a freeBSD install guide would look confusing.

Stick it in here for now and we can always migrate in later.

**Pull request merged**
