### PR TITLE
Added agent UUID in verifier IMA log message

### PR DESCRIPTION
**Pull request by rajdroid**
Currently, when several agents are polled from the verifier the same
message is printed for each of them. This is ambiguous for the user,
as it provides no info to the user. This change will add agent UUID
in a log message to distinguish between more than one agent.

Resolves: #230

### CODE REVIEW

**Comment by lukehinds** [comment]
Thanks @rajdroid , will test and review tomorrow!

**Comment by lukehinds** [comment]
@jetwhiz / @nabilschear can you have a quick check before I merge. It looks good to me during tests and happy to merge this.

**Comment by rajdroid** [comment]
Guys you can review these changes. Meanwhile, let me look at code quality. I think it is not up to the standards. @lukehinds please don't merge this until PR quality review is clean. I will update the review in sometime.

**Comment by lukehinds** [comment]
ack @rajdroid I will monitor and review -  charlie (jetwhiz) is likely on leave this week, but should pop up as well.

please squash your commits once your done.

**Comment by rajdroid** [comment]
@lukehinds I think we are good to go.

**Comment by lukehinds** [comment]
Great PR @rajdroid , I am happy to merge this now.

I would like to change the text, "Checking IMA Measurement.." in a later patch, but this is no reflection on what you have done here, I have been thinking about this for a while. Perhaps on Wednesday we can discuss this.

**Comment by rajdroid** [comment]
Thanks @lukehinds, and yeah we can have a discussion on Wednesday. I am on IST timezone, let me know the time and I'll try to align.

**Pull request merged**
