### PR TITLE
keylime-policy: use consistent names for create runtime

### PR DESCRIPTION
**Pull request by sergio-correia**
This PR has a few changes related to consistency within the policy tool, and has the following changes:

1) Let's keep option names consistent, i.e. use `--allowlist`/`--excludelist`, instead of `--allowlist`/`--exclude-list`
2) drop some confusing "short" shortcuts, like `-i` and `-A`, and keep long versions instead, for those
3) drop superfluous option `--use-ima-measurement-list`, as we already have `--ima-measurement-list`; the behavior is the following: if `--ima-measurement-list` is used without any argument, it will use the default IMA measurement list file, `/sys/kernel/security/ima/ascii_runtime_measurements`; if a parameter is given as argument, that parameter indicates the file to read as a source for the IMA measurement list
4) rename the tool itself from `keylime_policy` to `keylime-policy`

Fixes: #1610

### CODE REVIEW

**Comment by THS-on** [comment]
> rename the tool itself from keylime_policy to keylime-policy

Any reason for this, as all the other tools we have are keylime_XYZ?

**Comment by ansasaki** [comment]
> > rename the tool itself from keylime_policy to keylime-policy
> 
> Any reason for this, as all the other tools we have are keylime_XYZ?

I'm in favor of `keylime-policy` for ergonomic reasons. We are making all these changes to the tools to make them easier/more comfortable to use. I think that there is no reason to keep the name of the tool cumbersome to use  just because historically all the binaries in the project are cumbersome to use.

Moreover, the other `keylime_XYZ` are mostly run as services, not as command line tools. In my opinion, the `keylime_tenant` also should be renamed at some point as the name is misleading to newcomers. It is always a pain to explain that `keylime_tenant` is not a service, but a command-line tool.

**Comment by sergio-correia** [comment]
> > rename the tool itself from keylime_policy to keylime-policy
> 
> Any reason for this, as all the other tools we have are keylime_XYZ?

It will probably boil down to personal preference, in the end. In my opinion, this would be more in line with other command-line tools, and I actually find a dash even easier to use.

Just to have some anecdotal data to illustrate it from my system as I type this reply:
```
ls  /usr/bin/ | grep _ | wc -l
271

ls  /usr/bin/ | grep - | wc -l
1239
```

So, you see that while underscores are popular, dashes seem to be way more common.

I see your point that the other tools we have are keylime_XYZ, but I also I think we have a last chance to do better this time, as this one tool was not yet present in a releasem, so it technically does not yet exist :)

In practice, as the aim of the tool is to simplify user experience with handling Keylime policies, I think even this dash instead of underscore would play a role here -- it certainly would for me, at least.

**Comment by THS-on** [comment]
Yeah makes sense, then lets rename it and maybe do it with the rest of the commandline tools later.

**Comment by maugustosilva** [comment]
+1 on the suggestion of renaming the **user facing** utilities from `_` to `-`, for "ergonomic reasons" too. I have not thought through all the implications for the package maintainers, but we could even have a "transition phase" where the `keylime-*` utilities are symlinked to `keylime_`.

**Review by maugustosilva — APPROVED** [review]

**Comment by sergio-correia** [comment]
I dropped the temporary commit pointing the tests to my personal repo, to prevent it from being merged by accident. Tests will now fail as they need https://github.com/RedHat-SP-Security/keylime-tests/pull/657 merged, which updates the tests to confirm with the changes proposed here.

**Review by ansasaki — APPROVED** [review]

**Pull request merged**
