### PR TITLE
Tpm2 cleanups

### PR DESCRIPTION
**Pull request by williamcroberts**
I just grabbed the source, didn't get around to testing this patch fully. But I am looking at replacing your tpm2-tools invocations with python bindings to the TSS directly.

See https://github.com/tpm2-software/tpm2-pytss for details on the python bindings.

But I figured i'd throw this up and see if CI is ok with it, AFAICT it should work.

### CODE REVIEW

**Comment by lukehinds** [comment]
thanks @williamcroberts !

travis is not playing nice with us at the moment, see https://github.com/keylime/keylime/issues/264 , I will try and look at this over the next day or so. I will also test this patch you locally.

There is also an easy method to test patches locally in a container. https://keylime-docs.readthedocs.io/en/latest/developers.html#docker-development-environment - just make sure you update the image tags to [v5.5.0](https://hub.docker.com/layers/lukehinds/keylime-ci-tpm20/v550/images/sha256-14351d5d14d0dd7af7a453de30fc910e319bf04b3ec52dd89743e460a611de8b?context=explore)

We have considered direct tss direct coms before and were open and receptive to the idea, but no one had the bandwidth to take it on at the time. 

What do you consider to the the advantages here? One would be less dependencies required in Keylime which is useful for embedded / IoT. Would there be any dependency requirements for `tpm2_abrmd` , at the moment we prefer having both the kernel resource manager and tpm2_abrmd as options, as the kernel rm is useful for smaller devices and containers where they often don't run systemd / dbus.

**Comment by williamcroberts** [comment]
> thanks @williamcroberts !
> 
> travis is not playing nice with us at the moment, see #264 , I will try and look at this over the next day or so. I will also test this patch you locally.
> 
> There is also an easy method to test patches locally in a container. https://keylime-docs.readthedocs.io/en/latest/developers.html#docker-development-environment - just make sure you update the image tags to [v5.5.0](https://hub.docker.com/layers/lukehinds/keylime-ci-tpm20/v550/images/sha256-14351d5d14d0dd7af7a453de30fc910e319bf04b3ec52dd89743e460a611de8b?context=explore)
> 

Perfect, that was the type of info I was looking for!

> We have considered direct tss direct coms before and were open and receptive to the idea, but no one had the bandwidth to take it on at the time.

We would do it.

> 
> What do you consider to the the advantages here? One would be less dependencies required in Keylime which is useful for embedded / IoT. Another would be less of a moving target keeping up with changes to `tpm2_tools` (e.g. different args implemented) Would there be any dependency

Yes exactly. You could dump all the tooling requirements, you would just have the TSS (which you already have for tools) and the bindings (which would be new, but you already have Python, so...).

requirements on `tpm2_abrmd` , at the moment we prefer having both the kernel resource manager and tpm2_abrmd as options, as the kernel rm is useful for smaller devices and containers where they often don't run systemd / dbus.

The TCTI configuration wouldn't change. The TSS stack was built on being able to load arbitrary TCTIs. We created the TCTI loader library specifically so configuration across tooling would be consistent and it appears the python bindings have that.

**Comment by lukehinds** [comment]
hi @williamcroberts 

just reverting back CI to using tpm2-abrmd, we get the following when using an emulator with `TPM2TOOLS_TCTI="mssim:host=localhost,port=2321"`

```
Exception: Command: tpm2_createak -C 0x81000000 -c /var/lib/keylime/secure/tmprmvj05gb -G rsa -g sha256 -s rsassa -u /tmp/tmpyz8_t5ys -f pem -p L8ajOfTRlv0PtKVImN2r -P keylime returned 1, expected 0, output [], stderr [b'WARNING:esys:src/tss2-esys/api/Esys_Create.c:370:Esys_Create_Finish() Received TPM Error \n', b'ERROR:esys:src/tss2-esys/api/Esys_Create.c:120:Esys_Create() Esys Finish ErrorCode (0x00000902) \n', b'ERROR: Esys_Create(0x902) - tpm:warn(2.0): out of memory for object contexts\n', b'ERROR: Unable to run tpm2_createak\n']
```
I believe this says that the emu doesn't have more free memory to store transient objects in its RAM as we are not using a resource manager.

is it possible to use the emulator with the kernel resource emulator? 

p.s. I spoke with @jetwhiz yesterday and he is supportive of the TSS port. If you can try to drop into our meeting tomorrow...details are here: https://github.com/keylime/meetings/blob/master/README.md

**Comment by williamcroberts** [comment]
> hi @williamcroberts
> 
> just reverting back CI to using tpm2-abrmd, we get the following when using an emulator with `TPM2TOOLS_TCTI="mssim:host=localhost,port=2321"`

How does that revert back to using tpm2-abrmd? That line uses the emulator directly, so no RM.

> 
> ```
> Exception: Command: tpm2_createak -C 0x81000000 -c /var/lib/keylime/secure/tmprmvj05gb -G rsa -g sha256 -s rsassa -u /tmp/tmpyz8_t5ys -f pem -p L8ajOfTRlv0PtKVImN2r -P keylime returned 1, expected 0, output [], stderr [b'WARNING:esys:src/tss2-esys/api/Esys_Create.c:370:Esys_Create_Finish() Received TPM Error \n', b'ERROR:esys:src/tss2-esys/api/Esys_Create.c:120:Esys_Create() Esys Finish ErrorCode (0x00000902) \n', b'ERROR: Esys_Create(0x902) - tpm:warn(2.0): out of memory for object contexts\n', b'ERROR: Unable to run tpm2_createak\n']
> ```
> 
> I believe this says that the emu doesn't have more free memory to store objects in its RAM as we are not using a resource manager.

Yeah pretty much. So it appears you stopped using tpm2-abrmd and are attempting to go directly at the simulator. You could manually flush the objects via tpm2_flushcontext.

I don't think theirs a simple way to plumb the software simulator into the kernel. Their is this project, but AFAICT/AFAIK, it will create /dev nodes, but they are via CUSE, and thus will not be integrated into the TPM framework that includes the rm nodes.

I think you would have better luck getting tpm2-abrmd to work. What exactly is your issues?

> 
> This is in a container, interestingly it works ok in a vm, so I am bit quizzed and feel I might not have the full picture yet.

I've bumped into container issues before. But I can't seem to find any messages in the checkers on this PR. Can you point me where I can view the error logs?

> 
> is it possible to use the emulator with the kernel resource emulator somehow? I have only seen the kern RM as a character device, whereas the mssim emulator is a network service

Not that I know of.

> 
> p.s. I spoke with @jetwhiz yesterday and he is supportive of the TSS port. If you can try to drop into our meeting tomorrow...details are here: https://github.com/keylime/meetings/blob/master/README.md

Sure I can do that.

**Comment by lukehinds** [comment]
>  just reverting back CI to using tpm2-abrmd, we get the following when using an emulator with TPM2TOOLS_TCTI="mssim:host=localhost,port=2321"

> How does that revert back to using tpm2-abrmd? That line uses the emulator directly, so no RM.

I phrased that badly:

I am going to revert back to CI using tpm2-abrmd again, as we get the following when using an emulator with TPM2TOOLS_TCTI set to "mssim:host=localhost,port=2321"

[error]

**Comment by jetwhiz** [comment]
> 
> 
> hi @williamcroberts
> 
> just reverting back CI to using tpm2-abrmd, we get the following when using an emulator with `TPM2TOOLS_TCTI="mssim:host=localhost,port=2321"`
> 
> ```
> Exception: Command: tpm2_createak -C 0x81000000 -c /var/lib/keylime/secure/tmprmvj05gb -G rsa -g sha256 -s rsassa -u /tmp/tmpyz8_t5ys -f pem -p L8ajOfTRlv0PtKVImN2r -P keylime returned 1, expected 0, output [], stderr [b'WARNING:esys:src/tss2-esys/api/Esys_Create.c:370:Esys_Create_Finish() Received TPM Error \n', b'ERROR:esys:src/tss2-esys/api/Esys_Create.c:120:Esys_Create() Esys Finish ErrorCode (0x00000902) \n', b'ERROR: Esys_Create(0x902) - tpm:warn(2.0): out of memory for object contexts\n', b'ERROR: Unable to run tpm2_createak\n']
> ```
> 
> I believe this says that the emu doesn't have more free memory to store objects in its RAM as we are not using a resource manager.
> 
> This is in a container, interestingly it works ok in a vm, so I am bit quizzed and feel I might not have the full picture yet.
> 
> is it possible to use the emulator with the kernel resource emulator somehow? I have only seen the kern RM as a character device, whereas the mssim emulator is a network service
> 
> p.s. I spoke with @jetwhiz yesterday and he is supportive of the TSS port. If you can try to drop into our meeting tomorrow...details are here: https://github.com/keylime/meetings/blob/master/README.md

It's really cool to see some TSS python bindings being worked on, thanks @williamcroberts !  As @lukehinds mentioned, this is definitely something that we've been considering for Keylime, which would also solve issues with us having to execute command line binaries from within Python (and remove more dependencies).  

Let me know if you need any help with this effort, or if you have any questions about how Keylime is set up, organized, etc.

**Comment by williamcroberts** [comment]
> > hi @williamcroberts
> > just reverting back CI to using tpm2-abrmd, we get the following when using an emulator with `TPM2TOOLS_TCTI="mssim:host=localhost,port=2321"`
> > ```
> > Exception: Command: tpm2_createak -C 0x81000000 -c /var/lib/keylime/secure/tmprmvj05gb -G rsa -g sha256 -s rsassa -u /tmp/tmpyz8_t5ys -f pem -p L8ajOfTRlv0PtKVImN2r -P keylime returned 1, expected 0, output [], stderr [b'WARNING:esys:src/tss2-esys/api/Esys_Create.c:370:Esys_Create_Finish() Received TPM Error \n', b'ERROR:esys:src/tss2-esys/api/Esys_Create.c:120:Esys_Create() Esys Finish ErrorCode (0x00000902) \n', b'ERROR: Esys_Create(0x902) - tpm:warn(2.0): out of memory for object contexts\n', b'ERROR: Unable to run tpm2_createak\n']
> > ```
> > 
> > 
> > I believe this says that the emu doesn't have more free memory to store objects in its RAM as we are not using a resource manager.
> > This is in a container, interestingly it works ok in a vm, so I am bit quizzed and feel I might not have the full picture yet.
> > is it possible to use the emulator with the kernel resource emulator somehow? I have only seen the kern RM as a character device, whereas the mssim emulator is a network service
> > p.s. I spoke with @jetwhiz yesterday and he is supportive of the TSS port. If you can try to drop into our meeting tomorrow...details are here: https://github.com/keylime/meetings/blob/master/README.md
> 
> It's really cool to see some TSS python bindings being worked on, thanks @williamcroberts ! As @lukehinds mentioned, this is definitely something that we've been considering for Keylime, which would also solve issues with us having to execute command line binaries from within Python (and remove more dependencies).
> 
> Let me know if you need any help with this effort, or if you have any questions about how Keylime is set up, organized, etc.

Eventually I'll get to it, but it's not my current highest priority, but I will ask questions as I need them.

**Pull request closed without merging**
