### PR TITLE
Rename keylime_agent_secure.mount to comply policy

### PR DESCRIPTION
**Pull request by kkaarreell**
Filename keylime_agent_secure.mount does not comply systemd policy.

Per systemd.mount man page:

    Where=

    Takes an absolute path of a directory of the mount point.
    If the mount point does not exist at the time of mounting,
    it is created. This string must be reflected in the unit
    filename.

Correct name of a unit file mounting /var/lib/keylime/secure is var-lib-keylime-secure.mount

Signed-off-by: Karel Srot <ksrot@redhat.com>

### CODE REVIEW

**Comment by kkaarreell** [comment]
This resolves https://github.com/keylime/keylime/issues/1281

**Review by THS-on — APPROVED** [review]
LGTM

**Comment by sergio-correia** [comment]
We should probably update the `installer.sh` script that lives under `services/`, as I think it uses the old unit name.

**Comment by sergio-correia** [comment]
Please dismiss the previous comment; somehow I missed that the file in question was updated within this PR...

**Comment by aplanas** [comment]
Ouch my bad. I think that I make wrong name at the beginning and I renamed that later in the package.

**Pull request merged**
