### PR TITLE
Seperated cfssl server from ca_impl_cfssl.py

### PR DESCRIPTION
**Pull request by bu3alwa**
WIP #145

### CODE REVIEW

**Comment by lukehinds** [comment]
@bu3alwa 

Happy to help out with this one, but will need what your current set up steps are (how you run cfssl etc). I have your patch set up on machine at home.

**Comment by lukehinds** [comment]
some debug, the error you posted to gitter `couldn't initialize signer: {"code":2000,"message":"Unknown private key error"}` is because we need to pass in the ca key/cert.

You can debug this by adding a print debug here:

```
cmd = shlex.split(cmd)
print('cmd:', cmd)
cfsslproc = subprocess.Popen(cmd,env=env,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,universal_newlines=True)
```

```
[root@remote ~]# keylime_verifier 
Using config file /etc/keylime.conf
2020-04-21 11:08:21.529 - keylime.cloudverifier - INFO - Starting Cloud Verifier (tornado) on port 8881, use <Ctrl-C> to stop
2020-04-21 11:08:21.529 - keylime.cloudverifier_common - INFO - Setting up TLS...
2020-04-21 11:08:21.529 - keylime.cloudverifier_common - INFO - Generating a new CA in /var/lib/keylime/cv_ca and a client certificate for connecting
2020-04-21 11:08:21.529 - keylime.cloudverifier_common - INFO - use keylime_ca -d /var/lib/keylime/cv_ca to manage this CA
2020-04-21 11:08:21.529 - keylime.cloudverifier_common - WARNING - CAUTION: using default password for CA, please set private_key_pw to a strong password
cmd: cfssl serve -loglevel=1  
2020-04-21 11:08:22.025 - keylime.secure_mount - INFO - mounting secure storage location /var/lib/keylime/secure on tmpfs
cmd: cfssl serve -loglevel=1  -ca-key /var/lib/keylime/secure/ca-key.pem -ca cacert.crt 
2020-04-21 11:08:22.309 - keylime.ca-util - INFO - CA certificate created successfully in /var/lib/keylime/cv_ca
cmd: cfssl serve -loglevel=1 -config=/var/lib/keylime/secure/cfsslconfig.yml -ca-key /var/lib/keylime/secure/ca-key.pem -ca cacert.crt 
2020-04-21 11:08:22.824 - keylime.ca-util - INFO - Created certificate for name remote successfully in /var/lib/keylime/cv_ca
cmd: cfssl serve -loglevel=1 -config=/var/lib/keylime/secure/cfsslconfig.yml -ca-key /var/lib/keylime/secure/ca-key.pem -ca cacert.crt 
2020-04-21 11:08:23.392 - keylime.ca-util - INFO - Created certificate for name client successfully in /var/lib/keylime/cv_ca
2020-04-21 11:08:23.393 - keylime.cloudverifier - INFO - Starting service for revocation notifications on port 8992
```

This is looking like we might need to reconsider how we are doing this, as the verifier seems to set up and tear down cfssl (as you can see from the multiple times this occurs).

Keep this patch up, and I will try to look into this more, or if you want to keep momentum then you could look at the steps where start|stop of cfssl occurs and what keys/certs it requires at those junctures.

**Comment by bu3alwa** [comment]
Yea I have been working on decoupling some of that would you like me to post what i have so far?

**Comment by bu3alwa** [comment]
@lukehinds would it be possible to have a different directory for cfssl if chosen to run on the machine with its ca's? so like `/var/lib/keylime/cfssl/`. It looks like to be the best option imo.

**Comment by lukehinds** [comment]
hey @bu3alwa 

Whats the steps to run this? 

I have `ca_impl_cfssl.py` set in `keylime.conf` and then start the verifier:

```
2020-05-11 08:07:03.548 - keylime.cloudverifier - INFO - Starting Cloud Verifier (tornado) on port 8881, use <Ctrl-C> to stop
2020-05-11 08:07:03.550 - keylime.cloudverifier_common - INFO - Setting up TLS...
2020-05-11 08:07:03.550 - keylime.cloudverifier_common - INFO - Generating a new CA in /var/lib/keylime/cv_ca and a client certificate for connecting
2020-05-11 08:07:03.551 - keylime.cloudverifier_common - INFO - use keylime_ca -d /var/lib/keylime/cv_ca to manage this CA
2020-05-11 08:07:03.551 - keylime.cloudverifier_common - WARNING - CAUTION: using default password for CA, please set private_key_pw to a strong password
Traceback (most recent call last):
  File "/usr/local/bin/keylime_verifier", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/keylime/cmd/verifier.py", line 30, in main
    cloud_verifier_tornado.main()
  File "/usr/local/lib/python3.7/site-packages/keylime/cloud_verifier_tornado.py", line 681, in main
    context = cloud_verifier_common.init_mtls()
  File "/usr/local/lib/python3.7/site-packages/keylime/cloud_verifier_common.py", line 131, in init_mtls
    ca_util.cmd_init(tls_dir)
  File "/usr/local/lib/python3.7/site-packages/keylime/ca_util.py", line 146, in cmd_init
    cacert, ca_pk = ca_impl.get_cacert()
  File "/usr/local/lib/python3.7/site-packages/keylime/ca_impl_cfssl.py", line 67, in get_cacert
    body = post_cfssl('api/v1/cfssl/info')
TypeError: post_cfssl() missing 1 required positional argument: 'data'
```

I get the following for `start_cfssl`

```
start_cfssl
Traceback (most recent call last):
  File "/usr/local/bin/start_cfssl", line 11, in <module>
    load_entry_point('keylime==1.2', 'console_scripts', 'start_cfssl')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2792, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('console_scripts', 'start_cfssl') not found
```

Regarding the directory I see no issue here, we just might need to be mindful that the tenant and verifier have their own local folders. @jetwhiz might have been insight into how things are set up here.

**Comment by bu3alwa** [comment]
@lukehinds its not running yet I just needed a reply to keep working on it. I might need help with the config though not sure who categories or their passwords are set.

**Comment by THS-on** [comment]
#1012 removed CFSSL support, so I'm closing this.

**Pull request closed without merging**
