### PR TITLE
Full removal of vTPM support

### PR DESCRIPTION
**Pull request by THS-on**
Keylime no longer supports vTPM 1.2 from Xen and swtpm + libvirt never supported it for TPM 2.0, so we now remove it completely.

### CODE REVIEW

**Comment by THS-on** [comment]
@kkaarreell this PR removes the `--vtpm_policy` option from the tenant. So once this gets merged the tests should be adjusted to reflect that.

**Comment by kkaarreell** [comment]
> @kkaarreell this PR removes the `--vtpm_policy` option from the tenant. So once this gets merged the tests should be adjusted to reflect that.

I will prepare PR doing that.

**Comment by kkaarreell** [comment]
> > @kkaarreell this PR removes the `--vtpm_policy` option from the tenant. So once this gets merged the tests should be adjusted to reflect that.
> 
> I will prepare PR doing that.

Done, you can rerun your tests.

**Review by axelsimon — APPROVED** [review]
Looks good to me. However, given this bundles a destructive action (db migration script dropping columns), we need to issue a clear warning to users of vTPM (are there any?) that this will do that.

**Comment by THS-on** [comment]
> Looks good to me. However, given this bundles a destructive action (db migration script dropping columns), we need to issue a clear warning to users of vTPM (are there any?) that this will do that.

There was never working vTPM support for TPM 2.0, so I am pretty sure that nobody using Keylime version 6.0.0 and up has any use for that feature. I think we can remove it without any extra warnings.

**Comment by maugustosilva** [comment]
@axelsimon I second @THS-on evaluation, even though none of us have hard evidence at the moment. To be best of my knowledge, nobody has ever used vTPM with Xen outside of the team who initially wrote the paper (implementing something akin to "deep quote", requiring both a pTPM and vTPM). On other hand, I have experienced heavy use of vTPM with libvirt, which never required the "vTPM" support on keylime (as it treats the vTPM just like any other pTPM).

**Review by maugustosilva — APPROVED** [review]

**Pull request merged**
