### PR TITLE
Allow agents to specify a contact ip address and port for the tenant and CV 

### PR DESCRIPTION
**Pull request by THS-on**
Implementation of enhancement proposal keylime/enhancements#50.

Currently tests are missing but I'll add them once I figure out how to run the restful test locally.

### CODE REVIEW

**Comment by maugustosilva** [comment]
Hey, I don't think it is quite working yet. I believe you forgot to add a column to `verifiermain` table... here is what I see on the `verifier` log. At the beginning, the alembic migration is executed

```
2021-07-07 20:34:10.943 - alembic.runtime.migration - INFO - Running upgrade b4d024197413 -> f82c4252bc4f, Add ip and port to registrar
2021-07-07 20:34:10.943 - alembic.runtime.migration - DEBUG - update b4d024197413 to f82c4252bc4f
```

However, when I tried to add `agents` to a `verifier`, here is what I see:

```
2021-07-08 14:33:47.623 - keylime.cloudverifier_common - DEBUG - for nonce:           WHYWyvBWCFMYm5Gpwz2T
2021-07-08 14:33:47.624 - keylime.cloudverifier_common - DEBUG - received public key: None
2021-07-08 14:33:47.624 - keylime.cloudverifier_common - DEBUG - received ima_measurement_list    False
2021-07-08 14:33:47.624 - keylime.cloudverifier_common - DEBUG - received boot log    True
2021-07-08 14:33:47.720 - keylime.cloudverifier - ERROR - SQLAlchemy Error: Entity '<class 'keylime.db.verifier_db.VerfierMain'>' has no property 'registrar_data'
2021-07-08 14:33:47.720 - keylime.cloudverifier - DEBUG - Setting up callback to check again in 2.000000 seconds
```

**Comment by THS-on** [comment]
@maugustosilva I've renamed `registrar_keys` to `registrar_data` but forgot to add the change that adds this to the `exclude_db` list. Now this change is included in this PR.

I've now split up my commit into smaller ones and extended the tests.

**Comment by maugustosilva** [comment]
so, I tested your PR, and the problem is that you're now breaking the `update` command on `keylime_tenant`. Normally, an `update` optionally deletes the `agent` on the `verifier` database if it finds it there, and then re-adds it. 

In your current code, whenever I try use `update` to `add` an `agent`, I see an error message indicating that the `agent` does not exist on the `verifier` is printed out (which is perfectly fine) and then the CLI just ends (this is the problem). 

Allow me to attempt to illustrate with an example:

**CORRECT**
```
[root@css-flex14vm1 tmp]# /usr/local/bin/keylime_tenant -c update -t 100.64.14.15 -v 100.64.14.13 -u EB7CD2DF-9A40-5019-830E-D5805FC9276F --no-verifier-check --cert /var/lib/keylime/ca/EB7CD2DF-9A40-5019-830E-D5805FC9276F
Using config file /etc/keylime.conf
2021-07-13 19:59:11.891 - keylime.tpm - INFO - TPM2-TOOLS Version: 5.0
2021-07-13 19:59:11.896 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2021-07-13 19:59:11.896 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x408000
2021-07-13 19:59:11.897 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x808000
Please enter the password to decrypt your keystore:
2021-07-13 19:59:14.986 - keylime.ca-util - INFO - Creating cert package for EB7CD2DF-9A40-5019-830E-D5805FC9276F in EB7CD2DF-9A40-5019-830E-D5805FC9276F-pkg.zip
2021-07-13 19:59:15.088 - keylime.ca-util - INFO - Creating cert package for RevocationNotifier in RevocationNotifier-pkg.zip
2021-07-13 19:59:15.095 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): 100.64.14.13:8881
/usr/lib/python3.8/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2021-07-13 19:59:15.118 - urllib3.connectionpool - DEBUG - https://100.64.14.13:8881 "DELETE /agents/EB7CD2DF-9A40-5019-830E-D5805FC9276F HTTP/1.1" 404 60
2021-07-13 19:59:15.119 - keylime.tenant - ERROR - Response code 404: agent id not found
2021-07-13 19:59:15.121 - keylime.tenant - DEBUG - b64_v: EjizymAw6x1X8w0/v59qCfmr6DlqcBi9hbo4DqjMjgA=
2021-07-13 19:59:15.123 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): 100.64.14.13:8881
/usr/lib/python3.8/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2021-07-13 19:59:15.152 - urllib3.connectionpool - DEBUG - https://100.64.14.13:8881 "POST /agents/EB7CD2DF-9A40-5019-830E-D5805FC9276F HTTP/1.1" 200 49
2021-07-13 19:59:15.156 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 100.64.14.15:9002
2021-07-13 19:59:15.507 - urllib3.connectionpool - DEBUG - http://100.64.14.15:9002 "GET /quotes/identity?nonce=IFnXdDb1ldt8aEfvtfsU HTTP/1.1" 200 None
2021-07-13 19:59:15.509 - keylime.tenant - DEBUG - Agent_quote received quote: reJz7H+Ls3iDBoMTArWejv1Nb5U/r3ptSzlOurWE667LlTHfg0kPlXdfvNp95dYJBxNMtLyLFJckwJ6XEItE1rawkrTiUAQT0JhwDkswgJqOCOJskg5iZGYjNwM3MCCQVHs42mKsv8czp0ULvd3+yL8y+yrSwJKHU8u3xFt5lyheudQMAlAQvrg==:eJwBBgH5/gAUAAsBAKxFoR6rWXSe6GhjvPYsPPNyMhGYxsEfJxqPIAwHbaFThlYWDa8b3YOWJU54nxhVKwuWQVetP1vo89MSci3939F3Xuopb/RfApyYP9Nm2jFhPfNyYU+bi0iEwgs2zmonlTawTCAPyqFgfsihAC737FjRnNAS2OMXOv2VqjvJykXYkUyp2bMEZpSkbFNXZo77z8RI0FQ52QwTLiI/x7D2w2qszNBxfXMMVnPBU0qTE4Wh2yGz25UuK/JJ4EC1HzlsIvdoztXG6rganJew/KlOTl7PrNJXP3T/nIR6SJjNNU3I4bsRi8j43IeqP/Hmv7LOXt3ZWkDZdW/KUhVcdayB7dmgZII3:eJxjZGBg4GZgZmRgZBgwALKaCYgVGGTbX9Qq7Dsf+ipz44wVO+bKHTnXrr7DRT9rsQBr2Ka5fjGETFJgWNF5ge2o+gybO4+C3z3eH8jRf1hYrC1tojPrr4pldS62crT3zSigFgAAau0fKQ==
2021-07-13 19:59:15.510 - keylime.tenant - DEBUG - Agent_quote received public key: -----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArvSV5grhf4gnjFBUj2zG
FFLQQYeOIO6H4E7YHsTcY7wzbqCOeKEw4s1USvSDebQUGeERGzivwY1W0bHxFrFi
xKxHT0pyDVSkDdrB58q1882iwUt2LwH2AwjtyImnKVw0qIHWjk+tdWJsJB3NOiry
TboLfFVrnRIdvP8kHZpPfCgx6ZsUTjlEO+Sdyjx13JPBKGAfUeoXdTUUIb/yBxC2
kVfr5o05i4T15vZolH9z0m5RXsJaZDYz+BfPjDb1ro6S9WARnPjXjiZ11IKinA9h
Cewqw4ZpUeDZhpvX8M7DFb1+wyHxUBP8bTWWmoPd48q+1qgrzdcpENInDL6RiYho
qwIDAQAB
-----END PUBLIC KEY-----

2021-07-13 19:59:15.516 - keylime.tenant - DEBUG - Agent_quote received hash algorithm: sha256
2021-07-13 19:59:15.517 - keylime.tenant - DEBUG - Agent_quote received encryption algorithm: rsa
2021-07-13 19:59:15.517 - keylime.tenant - DEBUG - Agent_quote received signing algorithm: rsassa
2021-07-13 19:59:15.518 - keylime.registrar_client - WARNING - TLS is enabled.
2021-07-13 19:59:15.519 - keylime.registrar_client - INFO - Setting up client TLS...
2021-07-13 19:59:15.521 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): 100.64.14.12:8891
/usr/lib/python3.8/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2021-07-13 19:59:15.545 - urllib3.connectionpool - DEBUG - https://100.64.14.12:8891 "GET /agents/EB7CD2DF-9A40-5019-830E-D5805FC9276F HTTP/1.1" 200 None
2021-07-13 19:59:15.583 - keylime.tpm - DEBUG - EK cert matched cert: -----BEGIN CERTIFICATE-----
MIIEKTCCApGgAwIBAgIURnwelEgjA9th2L1FqyQyAM2n2BkwDQYJKoZIhvcNAQEL
BQAwHzEdMBsGA1UEAxMUc3d0cG0tbG9jYWxjYS1yb290Y2EwHhcNMTkxMjA1MjA1
MjM5WhcNMjkxMjAyMjA1MjM5WjAYMRYwFAYDVQQDEw1zd3RwbS1sb2NhbGNhMIIB
ojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEA0lziafQmkSNsI8aaCsuX43Bq
91t/PI9DVmwqmnJ19Hb+bCmPZBCjWZtBy7GjBw10E9GmZL7Vc5ss6CrROe+njvg2
TZuIR9WuWU9SXQvxYi6S8mU+Ajnuc0VAOzAVPU64K/aibg43j+SsI/qIOfKMK+4M
an9SQo9p5bOxxGT+OG3kbnXrpwIbgLKld3TS9cEHroJCjoCXxv8mJtBWr/l0Q/Rh
LhtdI0ogaeumCIDb0lbrla6dYK4XsqM/N7OhLuoQXgDWWPb83PcPb2C09x+eyTHr
jiUWzx83teBQ5NzYKxo9OtvubH8W3/03RbF2PbQ+qJGloH5lDSkHvz//X12URaXf
pmIPSJTgolFOCmbOlv6j9l6fyAkOhMFsVhMc0tXn2IfVIhxNM5E3iItJ8gp5/d9e
1a630EsNGks6QgjZp8hAVBpQIa6wexHadq+Vc2pilVmiI0kHso9+xtOWIv5224+S
EiwBdySLGjduX1e5RwQRYPg7BnfIPm+iW34LmxI1AgMBAAGjZDBiMA8GA1UdEwEB
/wQFMAMBAf8wDwYDVR0PAQH/BAUDAwcEADAdBgNVHQ4EFgQUAiJ5i57zobbnpAOV
el7i7idsLPMwHwYDVR0jBBgwFoAU3q94WkEzwcw5D6lTXAZ68iSF5+IwDQYJKoZI
hvcNAQELBQADggGBAMi46eEExcjA5/A4ohGFRX9pDveYI1lEtZjpDyW/Lp/NQFV0
h2wyL9CUGCzs7votWbIS8KuShKxKnacKZ/W8hg5/funCXg6iu53GrLIygGQKQ3n3
MpaPJwmOcWXY5OGNpqa7uw/TJsl7oJ+3oDFzUHhnjfh3r2pxzsiWLFEetZXF63+n
ofSMOk5I6WOdUe+wrT/wz+44J4IkEDT7Do0piRShNAKa+LdD7bpqWZzsTkjLHpu1
tcEyA3at8IT8GD7gc6eqwy6PHUxVOz8RkTLeppdKN6zJNH8/f2ZeA+zwv1qMXOxR
Cod0RJlWoA8RGt9LQHl+2OOrIX/RNaGvpjiGVUKNXfWGMFv+2Yxto50nL23WhJEM
m5+VWLMb2i9Qxi9sUz55bj3ZTfdiiAZgbq487oM/x6bCBs0eVPPati1+9FrfNwXV
xPfu/reExH2Z1xPN7QbVnvhEbwlF7IHhEK65qgCSothcwEHQ1XjTJ8jEeWBmyo6q
LIzoIpPpZ6vtt5gs0Q==
-----END CERTIFICATE-----

2021-07-13 19:59:15.596 - keylime.tenant - INFO - Checking EK with script /usr/local/bin/ek_check
2021-07-13 19:59:15.636 - keylime.tenant - DEBUG - External check script successfully to validated EK
2021-07-13 19:59:15.637 - keylime.tenant - INFO - Quote from 100.64.14.15 validated
2021-07-13 19:59:15.639 - keylime.tenant - DEBUG - b64_encrypted_u: JeYTPhqdYVN4ZikBRd+TL4CVtwBBasm1H8rOeECTcM2fRPxLffnZDiEAlUNriqAAtU/yOk2BaN1JgeHyPbYttR6HG98tndi9M/vPNLJUIrUhJVSJK0RcUpIF80j+sh1JMOwGTxbqdmcU5YxiEgmLBgGOhFZQVMrezbQ4NWKqEy22UoSpYYJ22UFgsd0/JuYvcHsOR8lMtiPiopVSjI0NJTNmE9PC+zlz7oiigXr0jYCbiEknkbeCKUhopJtrfoXuxRHu5u+kyzEzCmvC/54tutcIs8zqWQtuJ6p2Phjf1Wp2f9HCvI22DEQHOolIv9uuw6kB7tiD+r6d/qH+w+7YjA==
2021-07-13 19:59:15.642 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 100.64.14.15:9002
2021-07-13 19:59:15.650 - urllib3.connectionpool - DEBUG - http://100.64.14.15:9002 "POST /keys/ukey HTTP/1.1" 200 None
```

**WRONG**
```
[root@css-flex14vm1 tmp]# /usr/local/bin/keylime_tenant -c update -t 100.64.14.15 -v 100.64.14.13 -u EB7CD2DF-9A40-5019-830E-D5805FC9276F --cert /var/lib/keylime/ca/EB7CD2DF-9A40-5019-830E-D5805FC9276F
Using config file /etc/keylime.conf
2021-07-13 16:00:59.589 - keylime.tpm - INFO - TPM2-TOOLS Version: 5.0
2021-07-13 16:00:59.594 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2021-07-13 16:00:59.594 - keylime.registrar_client - WARNING - TLS is enabled.
2021-07-13 16:00:59.596 - keylime.registrar_client - INFO - Setting up client TLS...
2021-07-13 16:00:59.600 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): 100.64.14.12:8891
/usr/lib/python3.8/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2021-07-13 16:00:59.628 - urllib3.connectionpool - DEBUG - https://100.64.14.12:8891 "GET /agents/EB7CD2DF-9A40-5019-830E-D5805FC9276F HTTP/1.1" 200 None
2021-07-13 16:00:59.632 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x408000
2021-07-13 16:00:59.632 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x808000
Please enter the password to decrypt your keystore:
2021-07-13 16:01:02.593 - keylime.ca-util - INFO - Creating cert package for EB7CD2DF-9A40-5019-830E-D5805FC9276F in EB7CD2DF-9A40-5019-830E-D5805FC9276F-pkg.zip
2021-07-13 16:01:02.692 - keylime.ca-util - INFO - Creating cert package for RevocationNotifier in RevocationNotifier-pkg.zip
2021-07-13 16:01:02.696 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): 100.64.14.13:8881
/usr/lib/python3.8/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2021-07-13 16:01:02.725 - urllib3.connectionpool - DEBUG - https://100.64.14.13:8881 "GET /agents/EB7CD2DF-9A40-5019-830E-D5805FC9276F HTTP/1.1" 404 60
2021-07-13 16:01:02.726 - keylime.tenant - ERROR - Agent EB7CD2DF-9A40-5019-830E-D5805FC9276F does not exist on the verifier. Please try to add or update agent
```

**Comment by THS-on** [comment]
@maugustosilva thank you for the report. 
I think we are running into a race condition with the verifier here. The agent is successfully deleted but the check in `do_cv` still returns that the agent is there. I've added a `sleep(2)` statement after the `mytenant.do_cvdelete(...)` in line 1215 and then it works as expected. I'll investigate this issue further why my changes caused this.

**Comment by THS-on** [comment]
@maugustosilva is there a reason that you omitted `--no-verifier-check` in the second example because after adding this it works as expected.
```
[root@localhost keylime]# keylime_tenant -c update -u D432FBB3-D2F1-4A97-9EF7-75BD81C00000 -f ../secret --no-verifier-check
Using config file /etc/keylime.conf
2021-07-14 08:34:08.174 - keylime.tpm - INFO - TPM2-TOOLS Version: 4.3.0
2021-07-14 08:34:08.177 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2021-07-14 08:34:08.177 - keylime.registrar_client - WARNING - TLS is enabled.
2021-07-14 08:34:08.177 - keylime.registrar_client - INFO - Setting up client TLS...
/usr/lib/python3.9/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2021-07-14 08:34:08.196 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x408000
2021-07-14 08:34:08.196 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x808000
/usr/lib/python3.9/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2021-07-14 08:34:08.234 - keylime.tenant - ERROR - Response code 404: agent id not found
/usr/lib/python3.9/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/lib/python3.9/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2021-07-14 08:34:08.425 - keylime.tenant - WARNING - DANGER: EK cert checking is disabled and no additional checks on EKs have been specified with ek_check_script option. Keylime is not secure!!
2021-07-14 08:34:08.426 - keylime.tenant - INFO - Quote from 127.0.0.1 validated
```

The race between tenant and I found is different from the issue that you have reported. It only happens if you are trying to update an agent that is already added to the CV and also happens on the master branch.

**Comment by maugustosilva** [comment]
> @maugustosilva is there a reason that you omitted `--no-verifier-check` in the second example because after adding this it works as expected.
> 
> ```
> [root@localhost keylime]# keylime_tenant -c update -u D432FBB3-D2F1-4A97-9EF7-75BD81C00000 -f ../secret --no-verifier-check
> Using config file /etc/keylime.conf
> 2021-07-14 08:34:08.174 - keylime.tpm - INFO - TPM2-TOOLS Version: 4.3.0
> 2021-07-14 08:34:08.177 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
> 2021-07-14 08:34:08.177 - keylime.registrar_client - WARNING - TLS is enabled.
> 2021-07-14 08:34:08.177 - keylime.registrar_client - INFO - Setting up client TLS...
> /usr/lib/python3.9/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   warnings.warn(
> 2021-07-14 08:34:08.196 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x408000
> 2021-07-14 08:34:08.196 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x808000
> /usr/lib/python3.9/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   warnings.warn(
> 2021-07-14 08:34:08.234 - keylime.tenant - ERROR - Response code 404: agent id not found
> /usr/lib/python3.9/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   warnings.warn(
> /usr/lib/python3.9/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   warnings.warn(
> 2021-07-14 08:34:08.425 - keylime.tenant - WARNING - DANGER: EK cert checking is disabled and no additional checks on EKs have been specified with ek_check_script option. Keylime is not secure!!
> 2021-07-14 08:34:08.426 - keylime.tenant - INFO - Quote from 127.0.0.1 validated
> ```
> 
> The race between tenant and I found is different from the issue that you have reported. It only happens if you are trying to update an agent that is already added to the CV and also happens on the master branch.

My apologies, you are correct! I was using an outdated version of my testing code, which omitted the `--no-verifier-check`. 

@mpeters LGTM. This PR passes successfully on our "private" end-to-end CI/CD.

**Review by maugustosilva — APPROVED** [review]

**Comment by THS-on** [comment]
I have updated the commits to fix some typos in the commit messages but the content hasn't changed.

**Pull request merged**
