### PR TITLE
By default use the kernel resource manager instead of tpm2-abrmd

### PR DESCRIPTION
**Pull request by THS-on**
The linux kernel starting with 4.12 ships with its own resource manager  which makes tpm2-abrmd not needed anymore for most use cases. This changes the installer script to not install tpm2-adrmd and changes the default to `device:/dev/tpmrm0`.

We already dropped the tpm2-abrmd dependency for the Debian package by setting that value manually.

### CODE REVIEW

**Comment by stefanberger** [comment]
I previously had tried to also run things inside a container without the tpm2-abrmd but had the impression that tools around quoting did require the tpm2-abrmd. So you are sure this works without it?

**Comment by THS-on** [comment]
If you are running a TPM emulator on the same system as the agent is running it might be still useful because there the kernel doesn't provide a resource manager.
Otherwise I've been testing it with libvirt + swtpm and it works as intended.

**Comment by stefanberger** [comment]
Patch LGTM.

**Review by mpeters — APPROVED** [review]
lgtm

**Pull request merged**
